### ISSUE TITLE
UnknownHostKey - can not fetch host-key from the injected gateway

### ISSUE THREAD

**Issue by martinvw** [abdallahghdiri/junit5-dummy-sftp-server#1]
Hello @abdallahghdiri,

I'm having some troubles when using your library, I'm unable to connect from my production code because a new host-key is generated every time. Since there is no way (yet) to fetch it the connection fails.

Would you be open to a PR which will solve that?

Thanks a lot!

**Comment by abdallahghdiri** [comment]
Hello @martinvw 

First of all thanks for your feedback.

If i understand correctly, you don't have a way to configure a simple a username/password authentication in your production code.

And if so, adding the support for Public Key Authentication (by injecting the private key through the [extension programmatic definition](https://github.com/abdallahghdiri/junit5-dummy-sftp-server#programmatic-definition)) would resolve your issue

**Comment by martinvw** [comment]
Thanks your prompt reply


No I'm referring to host keys as explained on https://www.ssh.com/ssh/host-key

**Comment by abdallahghdiri** [comment]
Ok so your production code fails if its does not already recognize the SFTP server host key which it can't because a new one a generated each time and it cannot currently be retrieved through the gateway

**Comment by martinvw** [comment]
Correct, so ideally I would like the host-key to be exposed like the port.

My test can then store it in a known keys file and production code can use it from there. For another flow I even like to test how to code behaves when it does not match.

**Comment by abdallahghdiri** [comment]
ok cool i understand the situation better now, i must confess that i have not come across this issue before but i will create a pull request and look into it

**Comment by martinvw** [comment]
The reason you do not face the problem in the current test is because of the suppression of checks, however, I desire not to suppress those checks from my production code and would even like to validate the real behaviour.

The suppression is at the following fragment:

https://github.com/abdallahghdiri/junit5-dummy-sftp-server/blob/8366b271716caaded4aac13adf396fe53b09e2e6/src/test/java/com/ghdiri/abdallah/sftp/AbstractTest.java#L44-L46

**Comment by martinvw** [comment]
I'm working on a proposal to fix it for the `SampleDummySftpServerProgrammaticTest`

**Comment by abdallahghdiri** [comment]
@martinvw  I just released the version **0.3.0**. Thanks again for your contribution.
